

services:
  auth_db:
    image: postgres:17.5-alpine3.21
    container_name: auth_db
    restart: always
    environment:
      POSTGRES_USER: authentification-service
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: authentification-db
    ports:
      - "5444:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data

  sensor_db:
    image: postgres:17.5-alpine3.21
    container_name: sensor_db
    restart: always
    environment:
      POSTGRES_USER: sensor-service
      POSTGRES_PASSWORD: 12345f
      POSTGRES_DB: sensor-db
    ports:
      - "5445:5432"
    volumes:
      - sensor_data:/var/lib/postgresql/data

  alert_db:
    image: postgres:17.5-alpine3.21
    container_name: alert_db
    restart: always
    environment:
      POSTGRES_USER: alert-service
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: alert-db
    ports:
      - "5446:5432"
    volumes:
      - alert_data:/var/lib/postgresql/data
  
  profile-db:
    image: postgres:17.5-alpine3.21
    container_name: profile_db
    restart: always
    environment:
      POSTGRES_USER: profile-service
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: profile-db
    ports:
      - "5447:5432"
    volumes:
      - profile_data:/var/lib/postgresql/data

  vault:
    image: hashicorp/vault:latest
    container_name: dev-vault
    cap_add: ["IPC_LOCK"]
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    command: server -dev
    ports:
      - "8200:8200"
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: dev-keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: auth_db
      KC_DB_URL_PORT: "5432"
      KC_DB_URL_DATABASE: authentification-db
      KC_DB_USERNAME: authentification-service
      KC_DB_PASSWORD: 1234
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - auth_db
    restart: always

  mqtt:
    image: eclipse-mosquitto:2
    container_name: dev-mqtt
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mosquitto_sub -h 127.0.0.1 -p 1883 -t '$$SYS/broker/uptime' -C 1 -W 15 || exit 1",
        ]
      interval: 30s
      timeout: 5s
      retries: 3

  kafka:
    image: apache/kafka:4.1.1
    container_name: dev-kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: dev-kafka-ui
    restart: always
    ports:
      - "8088:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
  ml_predict_vital_signs:
    build:
      context: "../BabyGuardien-ML/BabyGuardian-TSBoost"
      dockerfile: "dockerfile"   # mets "Dockerfile" si ton fichier s'appelle Dockerfile
    container_name: ml_predict_vital_signs
    restart: always
    ports:
      - "5000:5000"
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - "../BabyGuardien-ML/BabyGuardian-TSBoost/models:/app/models:ro"
  risk-scoring-api:
    build:
      context: "../BabyGuardien-ML/babyguardian-risk-scoring-api"
      dockerfile: "dockerfile"
    container_name: risk_scoring_api
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - sensor_db
      - alert_db
      - mqtt
    environment:
      ARTIFACTS_DIR: "artifacts"
    volumes:
       - risk_artifacts:/app/artifacts
volumes:
  auth_data:
    driver: local
  sensor_data:
    driver: local
  alert_data:
    driver: local
  mosquitto_data:
    driver: local
  mosquitto_log:
    driver: local
  risk_artifacts:
    driver: local
  profile_data:
    driver: local
