version: "3.9"

services:
  auth_db:
    image: postgres:17.5-alpine3.21
    container_name: auth_db
    restart: always
    environment:
      POSTGRES_USER: authentification-service
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: authentification-db
    ports:
      - "5444:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data

  sensor_db:
    image: postgres:17.5-alpine3.21
    container_name: sensor_db
    restart: always
    environment:
      POSTGRES_USER: sensor-service
      POSTGRES_PASSWORD: 12345f
      POSTGRES_DB: sensor-db
    ports:
      - "5445:5432"
    volumes:
      - sensor_data:/var/lib/postgresql/data

  vault:
    image: hashicorp/vault:latest
    container_name: dev-vault
    cap_add: ["IPC_LOCK"]
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    command: server -dev
    ports:
      - "8200:8200"
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: dev-keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: auth_db
      KC_DB_URL_PORT: "5432"
      KC_DB_URL_DATABASE: authentification-db
      KC_DB_USERNAME: authentification-service
      KC_DB_PASSWORD: 1234
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin


    ports:
      - "8080:8080"
    depends_on:
      - auth_db
    restart: always
  mqtt:
    image: eclipse-mosquitto:2
    container_name: dev-mqtt
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    healthcheck:
      # IMPORTANT : échapper $ -> $$ pour éviter l'expansion par Compose
      test:
        [
          "CMD-SHELL",
          "mosquitto_sub -h 127.0.0.1 -p 1883 -t '$$SYS/broker/uptime' -C 1 -W 15 || exit 1",
        ]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  auth_data:
    driver: local
  sensor_data:
    driver: local
  alert_data:
    driver: local
  mosquitto_data:
    driver: local
  mosquitto_log:
    driver: local
#docker run --rm -it cloudflare/cloudflared:latest tunnel --url http://host.docker.internal:8080
